[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-cli"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = "0.19.1"

[dependencies]
anyhow                      = { workspace = true }
clap                        = { workspace = true, features = ["derive", "wrap_help"] }
colored                     = { workspace = true }
config-parser               = { workspace = true }
velox-genesis               = { workspace = true, features = ["metrics"] }
velox-httpd                 = { workspace = true, features = ["metrics", "tracing"] }
velox-indexer-clickhouse    = { workspace = true, features = ["async-graphql", "metrics", "tracing"] }
velox-indexer-sql           = { workspace = true, features = ["async-graphql", "metrics", "tracing"] }
velox-proposal-preparer     = { workspace = true, features = ["metrics"] }
velox-upgrade               = { workspace = true }
dialoguer                   = { workspace = true }
futures                     = { workspace = true }
bolt-app                    = { workspace = true, features = ["abci", "metrics", "tracing"] }
bolt-db-disk                = { workspace = true, features = ["metrics", "tracing"] }
bolt-httpd                  = { workspace = true, features = ["metrics", "tracing"] }
bolt-types                  = { workspace = true }
bolt-vm-rust                = { workspace = true }
home                        = { workspace = true }
indexer-cache               = { workspace = true, features = ["http-request-details", "metrics", "s3", "tracing"] }
indexer-hooked              = { workspace = true, features = ["metrics", "tracing"] }
indexer-httpd               = { workspace = true, features = ["metrics", "tracing"] }
indexer-sql                 = { workspace = true, features = ["async-graphql", "metrics", "tracing"] }
libc                        = { workspace = true }
metrics                     = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
opentelemetry               = { workspace = true }
opentelemetry-otlp          = { workspace = true }
opentelemetry_sdk           = { workspace = true }
sentry                      = { workspace = true }
serde                       = { workspace = true }
tokio                       = { workspace = true }
tower                       = { workspace = true, features = ["full"] }
tower-abci                  = { workspace = true }
tracing                     = { workspace = true }
tracing-opentelemetry       = { workspace = true }
tracing-subscriber          = { workspace = true }

[[bin]]
name = "velox"
path = "src/main.rs"
