http:
  middlewares:
    {{ velox_network }}-cors-velox:
      headers:
        accessControlAllowOriginListRegex:
          - ^https://([a-z0-9-]+\.)*velox\.zone$
          - ^https://([a-z0-9-]+\.)*velox\.exchange$
          - ^https://([a-z0-9-]+\.)*velox-portal\.pages\.dev$
        accessControlAllowMethods: ["GET","POST","OPTIONS"]
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
          - Accept
          - X-Requested-With
          - sentry-trace
          - baggage
        accessControlAllowCredentials: true
        addVaryHeader: true
        accessControlMaxAge: 600

  services:
    {{ velox_network }}-velox:
      loadBalancer:
        servers:
          - url: "http://{{ deployment_name }}-velox-1:8080"
    {{ velox_network }}-faucet_bot:
      loadBalancer:
        servers:
          - url: "http://{{ deployment_name }}-faucet-bot-1:8082"
    {{ velox_network }}-graphiql:
      loadBalancer:
        servers:
          - url: "http://{{ deployment_name }}-graphiql-1:80"

  routers:
    {{ velox_network }}-main-backend:
      rule: "Host(`api-{{ velox_network }}-{{ hostname }}.{{ velox_domain }}`)"
      entryPoints:
        - "web"
      service: "{{ velox_network }}-velox"
      middlewares:
        - "{{ velox_network }}-cors-velox"

    {{ velox_network }}-main-backend-ssl:
      rule: "Host(`api-{{ velox_network }}-{{ hostname }}.{{ velox_domain }}`)"
      entryPoints:
        - "websecure"
      tls: {}
      service: "{{ velox_network }}-velox"
      middlewares:
        - "{{ velox_network }}-cors-velox"

    {{ velox_network }}-main-faucet_bot:
      rule: "Host(`faucet-{{ velox_network }}-{{ hostname }}.{{ velox_domain }}`)"
      entryPoints:
        - "web"
      service: "{{ velox_network }}-faucet_bot"
      middlewares:
        - "{{ velox_network }}-cors-velox"

    {{ velox_network }}-main-faucet_bot-ssl:
      rule: "Host(`faucet-{{ velox_network }}-{{ hostname }}.{{ velox_domain }}`)"
      entryPoints:
        - "websecure"
      tls: {}
      service: "{{ velox_network }}-faucet_bot"
      middlewares:
        - "{{ velox_network }}-cors-velox"

    {{ velox_network }}-main-graphiql:
      rule: "Host(`graphiql-{{ velox_network }}-{{ hostname }}.{{ velox_domain }}`)"
      entryPoints:
        - "web"
      service: "{{ velox_network }}-graphiql"

    {{ velox_network }}-main-graphiql-ssl:
      rule: "Host(`graphiql-{{ velox_network }}-{{ hostname }}.{{ velox_domain }}`)"
      entryPoints:
        - "websecure"
      tls: {}
      service: "{{ velox_network }}-graphiql"
