[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-testing"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
actix-web                = { workspace = true }
anyhow                   = { workspace = true }
async-graphql            = { workspace = true }
async-trait              = { workspace = true }
clickhouse               = { workspace = true, features = ["test-util"] }
velox-genesis            = { workspace = true }
velox-httpd              = { workspace = true, features = ["metrics", "tracing"] }
velox-indexer-clickhouse = { workspace = true, features = ["async-graphql", "metrics", "testing", "tracing"] }
velox-indexer-sql        = { workspace = true, features = ["async-graphql", "testing", "tracing"] }
velox-order-book         = { workspace = true }
velox-proposal-preparer  = { workspace = true }
velox-types              = { workspace = true, features = ["async-graphql"] }
bolt                     = { workspace = true }
bolt-app                 = { workspace = true }
bolt-db-disk             = { workspace = true }
bolt-db-memory           = { workspace = true }
bolt-httpd               = { workspace = true }
bolt-types               = { workspace = true, features = ["async-graphql"] }
bolt-vm-rust             = { workspace = true }
hex-literal              = { workspace = true }
hyperlane-testing        = { workspace = true }
hyperlane-types          = { workspace = true }
identity                 = { workspace = true }
indexer-cache            = { workspace = true, features = ["metrics", "tracing"] }
indexer-hooked           = { workspace = true, features = ["metrics", "tracing"] }
indexer-httpd            = { workspace = true, features = ["metrics"] }
indexer-sql              = { workspace = true, features = ["async-graphql", "testing", "tracing"] }
k256                     = { workspace = true }
pyth-client              = { workspace = true }
pyth-types               = { workspace = true }
sea-orm                  = { workspace = true }
serde                    = { workspace = true }
serde_json               = { workspace = true }
sha2                     = { workspace = true }
temp-rocksdb             = { workspace = true }
tokio                    = { workspace = true }

[dev-dependencies]
actix-service               = { workspace = true }
anyhow                      = { workspace = true }
assert-json-diff            = { workspace = true }
assertor                    = { workspace = true }
bip32                       = { workspace = true }
chrono                      = { workspace = true }
criterion                   = { workspace = true }
velox-account-factory       = { workspace = true, features = ["library"] }
velox-auth                  = { workspace = true }
velox-bank                  = { workspace = true, features = ["library"] }
velox-dex                   = { workspace = true, features = ["library"] }
velox-gateway               = { workspace = true, features = ["library"] }
velox-httpd                 = { workspace = true, features = ["metrics"] }
velox-mock-httpd            = { workspace = true }
velox-oracle                = { workspace = true, features = ["library"] }
velox-graphql-types         = { workspace = true }
velox-perps                 = { workspace = true, features = ["library"] }
velox-taxman                = { workspace = true, features = ["library"] }
eth-utils                   = { workspace = true }
graphql_client              = { workspace = true }
bolt-testing                = { workspace = true }
hex                         = { workspace = true }
home                        = { workspace = true }
indexer-disk-saver          = { workspace = true }
indexer-testing             = { workspace = true }
itertools                   = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
proptest                    = { workspace = true }
rand                        = { workspace = true }
reqwest                     = { workspace = true, features = ["json"] }
serde_json                  = { workspace = true }
test-case                   = { workspace = true }
tokio                       = { workspace = true, features = ["full"] }
tracing                     = { workspace = true }

[[bench]]
harness = false
name    = "benchmarks"
