[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-perps"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[features]
metrics = ["velox-primitives/metrics", "dep:metrics"]
tracing = ["velox-primitives/chrono", "dep:tracing"]

[dependencies]
anyhow                = { workspace = true }
velox-account-factory = { workspace = true }
velox-math            = { workspace = true }
velox-oracle          = { workspace = true }
velox-order-book      = { workspace = true }
velox-primitives      = { workspace = true }
velox-pyth-types      = { workspace = true }
velox-storage         = { workspace = true }
velox-types           = { workspace = true }
metrics               = { workspace = true, optional = true }
tracing               = { workspace = true, optional = true }

[dev-dependencies]
test-case = { workspace = true }
