[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-auth"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
alloy            = { workspace = true, features = ["dyn-abi", "eip712"] }
anyhow           = { workspace = true }
velox-primitives = { workspace = true }
velox-storage    = { workspace = true }
velox-types      = { workspace = true }
data-encoding    = { workspace = true }
hex              = { workspace = true }
sha2             = { workspace = true }

[dev-dependencies]
velox-eth-utils = { workspace = true }
velox-identity  = { workspace = true }
data-encoding   = { workspace = true }
hex-literal     = { workspace = true }
k256            = { workspace = true }
p256            = { workspace = true }
rand            = { workspace = true }
serde_json      = { workspace = true }
