[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-upgrade"
repository    = { workspace = true }
rust-version  = { workspace = true }

[dependencies]
velox-app        = { workspace = true }
velox-primitives = { workspace = true }
tracing          = { workspace = true }
