[package]
authors       = { workspace = true }
categories    = { workspace = true }
description   = "A minimalist implementation of Jellyfish Merkle tree (JMT)"
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-jmt"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
borsh            = { workspace = true, features = ["de_strict_order", "derive"] }
velox-app        = { workspace = true }
velox-primitives = { workspace = true }
velox-storage    = { workspace = true }
thiserror        = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
proptest    = { workspace = true }
test-case   = { workspace = true }
