set positional-arguments

# List available recipes
default:
  @just --list

docker-build-builder-images:
  docker buildx bake --push

  # Combine the two into a manifest
  docker buildx imagetools create -t ghcr.io/nabob-labs/laffer/native-builder:latest \
    ghcr.io/nabob-labs/laffer/native-builder:amd64 \
    ghcr.io/nabob-labs/laffer/native-builder:arm64
