- hosts: bots
  become: true
  become_user: "{{ deploy_user }}"
  collections:
    - community.docker
  tasks:
    - name: Stop and remove bots container
      docker_container:
        name: "{{ velox_network }}_bots"
        state: absent
        keep_volumes: false
      loop: "{{ velox_networks }}"
      loop_control:
        loop_var: velox_network
