[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-hyperlane-ism"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
anyhow                = { workspace = true }
velox-hyperlane-types = { workspace = true }
velox-primitives      = { workspace = true }
velox-storage         = { workspace = true }

[dev-dependencies]
velox-identity = { workspace = true }
hex-literal    = { workspace = true }
k256           = { workspace = true }
rand           = { workspace = true }
test-case      = { workspace = true }
