[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-genesis"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[features]
metrics = ["velox-oracle/metrics", "velox-perps/metrics"]

[dependencies]
anyhow                  = { workspace = true }
velox-account           = { workspace = true }
velox-account-factory   = { workspace = true }
velox-bank              = { workspace = true }
velox-gateway           = { workspace = true }
velox-hyperlane-ism     = { workspace = true }
velox-hyperlane-mailbox = { workspace = true }
velox-hyperlane-types   = { workspace = true }
velox-hyperlane-va      = { workspace = true }
velox-math              = { workspace = true }
velox-oracle            = { workspace = true }
velox-order-book        = { workspace = true }
velox-perps             = { workspace = true, features = ["tracing"] }
velox-primitives        = { workspace = true }
velox-types             = { workspace = true }
velox-vesting           = { workspace = true }
velox-vm-rust           = { workspace = true }
velox-warp              = { workspace = true }
serde                   = { workspace = true }
