[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-indexer-sql"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[lib]
path = "src/lib.rs"

[features]
async-graphql        = ["velox-primitives/async-graphql", "velox-types/async-graphql", "dep:async-graphql"]
http-request-details = []
metrics              = ["dep:metrics"]
testing              = []
tracing              = ["velox-disk-saver/tracing", "velox-indexer-cache/tracing", "dep:tracing"]

[dependencies]
anyhow              = { workspace = true }
async-graphql       = { workspace = true, optional = true }
async-stream        = { workspace = true }
async-trait         = { workspace = true }
velox-app           = { workspace = true }
velox-backtrace     = { workspace = true }
velox-disk-saver    = { workspace = true }
velox-indexer-cache = { workspace = true }
velox-primitives    = { workspace = true, features = ["chrono", "sea-orm"] }
velox-types         = { workspace = true, features = ["sea-orm"] }
itertools           = { workspace = true }
metrics             = { workspace = true, optional = true }
sea-orm             = { workspace = true }
sea-orm-migration   = { workspace = true }
serde               = { workspace = true }
serde_json          = { workspace = true }
sqlx                = { workspace = true }
tempfile            = { workspace = true }
thiserror           = { workspace = true }
tokio               = { workspace = true, features = ["sync"] }
tokio-stream        = { workspace = true }
tracing             = { workspace = true, optional = true }
uuid                = { workspace = true }

[dev-dependencies]
assertor  = { workspace = true }
test-case = { workspace = true }
