[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-upgrade"
repository    = { workspace = true }
rust-version  = { workspace = true }

[dependencies]
velox-order-book = { workspace = true }
velox-perps      = { workspace = true, features = ["library"] }
velox-types      = { workspace = true }
bolt             = { workspace = true }
bolt-app         = { workspace = true }
tracing          = { workspace = true }
