[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-backtrace"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[features]
default = ["derive"]
derive  = ["dep:velox-backtrace-derive"]

[dependencies]
anyhow                 = { workspace = true }
borsh                  = { workspace = true, features = ["derive"] }
velox-backtrace-derive = { path = "./derive", optional = true }
serde                  = { workspace = true, features = ["derive"] }

[dev-dependencies]
velox-backtrace = { workspace = true, features = ["derive"] } # the `derive` feature must be explicitly activated for the test
thiserror       = { workspace = true }
