[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "velox-vm-wasm"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
clru               = { workspace = true }
velox-app          = { workspace = true }
velox-backtrace    = { workspace = true }
velox-crypto       = { workspace = true }
velox-primitives   = { workspace = true }
data-encoding      = { workspace = true }
thiserror          = { workspace = true }
tracing            = { workspace = true }
wasmer             = { workspace = true, features = ["singlepass"] }
wasmer-middlewares = { workspace = true }

[dev-dependencies]
criterion      = { workspace = true }
velox-app      = { workspace = true, features = ["tracing"] }
velox-crypto   = { workspace = true }
velox-identity = { workspace = true }
velox-math     = { workspace = true }
velox-tester   = { workspace = true, features = ["library"] }
ed25519-dalek  = { workspace = true, features = ["batch", "digest"] }
k256           = { workspace = true }
p256           = { workspace = true }
rand           = { workspace = true }
test-case      = { workspace = true }
tokio          = { workspace = true }

[[bench]]
harness = false
name    = "benchmarks"
